# fly.toml app configuration file generated for datingapp2019570346 on 2024-05-15T10:54:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingapp2019570346'
primary_region = 'jnb'

[build]
  image = 'kyleloader/datingapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dfpjit3nq"
  CloudinarySettings__ApiKey="113713872542724"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
